## Carseats
#### CompPrice
#### Income
#### Advertising
#### Population
#### Price
#### Age
#### Education

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('Carseats.csv')
del data['ShelveLoc']
data.drop(data.columns[0], inplace=True, axis=1)
data['Urban'] = data.Urban.map({'Yes': 1, 'No':0 })
data['US'] = data.US.map({'Yes': 1, 'No':0 })
data.head(10)

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0   9.50        138      73           11         276    120   42         17   
1  11.22        111      48           16         260     83   65         10   
2  10.06        113      35           10         269     80   59         12   
3   7.40        117     100            4         466     97   55         14   
4   4.15        141      64            3         340    128   38         13   
5  10.81        124     113           13         501     72   78         16   
6   6.63        115     105            0          45    108   71         15   
7  11.85        136      81           15         425    120   67         10   
8   6.54        132     110            0         108    124   76         10   
9   4.69        132     113            0         131    124   76         17   

   Urban  US  
0      1   1  
1      1   1  
2      1   1  
3      1   1  
4      1   0  
5      0   1  
6      1   0  
7      1   1  
8      0   0  
9      0   1

### normalization

In [4]:
data_x = data[data.columns[1:]]
ss = StandardScaler()
ss.fit(data_x)
x_data_ss = ss.transform(data_x)
x_data_ss

array([[ 0.85045499,  0.15536099,  0.65717702, ...,  1.18444912,
         0.64686916,  0.74188112],
       [-0.91248434, -0.73906037,  1.40995711, ..., -1.4901134 ,
         0.64686916,  0.74188112],
       [-0.78189624, -1.20415947,  0.506621  , ..., -0.72595268,
         0.64686916,  0.74188112],
       ..., 
       [ 2.41751217, -1.52615116,  0.80773304, ...,  1.56652948,
         0.64686916,  0.74188112],
       [-1.63071888,  0.37002211,  0.05495295, ..., -0.72595268,
         0.64686916,  0.74188112],
       [ 0.58927879, -1.13260576, -0.99893918, ...,  0.80236876,
         0.64686916,  0.74188112]])

In [5]:
data_y = data['Sales']

### Linear regression

In [6]:
lm = LinearRegression()
lm.fit(x_data_ss,data_y)
lm.coef_

/Users/jlou/anaconda/lib/python3.5/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


array([ 1.4435384 ,  0.364764  ,  0.90956105, -0.02954468, -2.18592167,
       -0.72473507, -0.11071867, -0.07109871, -0.05086245])

### Lasso

In [7]:
from scipy.stats import uniform as sp_rand
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.grid_search import RandomizedSearchCV

/Users/jlou/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/jlou/anaconda/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [8]:
Lasso = Lasso()
Lasso.fit(x_data_ss,data_y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [9]:
# check the accuracy
Lasso.score(x_data_ss,data_y)

0.072284898947023057

In [10]:
# decision_function(lasso)
Lasso.coef_

array([ 0.        ,  0.        ,  0.        ,  0.        , -0.25502032,
       -0.        , -0.        , -0.        ,  0.        ])