## Auto
#### Cylinders
#### Displacement
#### Horsepower
#### Weight
#### Acceleration
#### Year
#### Origin


In [5]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv('Auto.csv')
del data['name']
data.drop(data.columns[0], inplace=True, axis=1)
data.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   
5  15.0          8         429.0         198    4341          10.0    70   
6  14.0          8         454.0         220    4354           9.0    70   
7  14.0          8         440.0         215    4312           8.5    70   
8  14.0          8         455.0         225    4425          10.0    70   
9  15.0          8         390.0         190    3850           8.5    70   

   origin  
0       1  
1       1  
2       1  
3       1  
4       1  
5       1  
6       1  
7       1  
8       1  
9       1

### normalization

In [3]:
data_x = data[data.columns[1:]]
ss = StandardScaler()
ss.fit(data_x)
x_data_ss = ss.transform(data_x)
x_data_ss

array([[ 1.48394702,  1.07728956,  0.66413273, ..., -1.285258  ,
        -1.62531533, -0.71664105],
       [ 1.48394702,  1.48873169,  1.57459447, ..., -1.46672362,
        -1.62531533, -0.71664105],
       [ 1.48394702,  1.1825422 ,  1.18439658, ..., -1.64818924,
        -1.62531533, -0.71664105],
       ..., 
       [-0.86401356, -0.56847897, -0.53247413, ..., -1.4304305 ,
         1.63640964, -0.71664105],
       [-0.86401356, -0.7120053 , -0.66254009, ...,  1.11008813,
         1.63640964, -0.71664105],
       [-0.86401356, -0.72157372, -0.58450051, ...,  1.40043312,
         1.63640964, -0.71664105]])

In [4]:
data_y = data['mpg']

### Linear regression

In [7]:
lm = LinearRegression()
lm.fit(x_data_ss,data_y)
lm.coef_

/Users/jlou/anaconda/lib/python3.5/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


array([-0.84051891,  2.07930256, -0.65163644, -5.49205044,  0.22201407,
        2.76211888,  1.14731588])

### Lasso

In [34]:
from scipy.stats import uniform as sp_rand
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.grid_search import RandomizedSearchCV

In [35]:
Lasso = Lasso()
Lasso.fit(x_data_ss,data_y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [36]:
# check the accuracy
Lasso.score(x_data_ss,data_y)

0.78840851356564279

In [38]:
# decision_function(lasso)
Lasso.coef_

array([-0.        , -0.        , -0.16773691, -4.54549985,  0.        ,
        1.99442996,  0.308293  ])