## Data description
#### temp
#### atemp
#### humidity
#### windspeed
#### hour 
#### month

In [6]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [7]:
data = pd.read_csv('bike-sharing-data.csv')
del data['casual']
del data['registered']
data.datetime = data.datetime.apply(pd.to_datetime)
data['month'] = data.datetime.apply(lambda x : x.month)
data['hour'] = data.datetime.apply(lambda x : x.hour)
data.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0 2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1 2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2 2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3 2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4 2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  count  month  hour  
0        81        0.0     16      1     0  
1        80        0.0     40      1     1  
2        80        0.0     32      1     2  
3        75        0.0     13      1     3  
4        75        0.0      1      1     4

### data normalization

In [9]:
data_x = data[['temp','atemp','humidity','windspeed','month','hour','holiday','workingday']]
ss = StandardScaler()
ss.fit(data_x)
x_data_ss = ss.transform(data_x)
x_data_ss

array([[-1.33366069, -1.09273697,  0.99321305, ..., -1.66894356,
        -0.17149048, -1.46067232],
       [-1.43890721, -1.18242083,  0.94124921, ..., -1.52434128,
        -0.17149048, -1.46067232],
       [-1.43890721, -1.18242083,  0.94124921, ..., -1.379739  ,
        -0.17149048, -1.46067232],
       ..., 
       [-0.80742813, -0.91395927, -0.04606385, ...,  1.36770431,
        -0.17149048,  0.68461625],
       [-0.80742813, -0.73518157, -0.04606385, ...,  1.51230659,
        -0.17149048,  0.68461625],
       [-0.91267464, -0.82486544,  0.21375537, ...,  1.65690887,
        -0.17149048,  0.68461625]])

In [10]:
data_y = data['count']

### linear regression

In [11]:
lm = LinearRegression()
lm.fit(x_data_ss,data_y)
lm.coef_

array([ 17.07484361,  37.89943319, -44.58510916,   2.8682513 ,
        25.72084951,  52.12093609,  -0.77912041,  -0.12240326])

### lasso

In [12]:
from scipy.stats import uniform as sp_rand
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.grid_search import RandomizedSearchCV

/Users/jlou/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Users/jlou/anaconda/lib/python3.5/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [13]:
Lasso = Lasso()
Lasso.fit(x_data_ss,data_y)

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [14]:
# check the accuracy
Lasso.score(x_data_ss,data_y)

0.33730150740212861

In [15]:
# decision_function(lasso)
Lasso.coef_

array([ 18.39723238,  35.9575794 , -43.81032937,   1.9333098 ,
        24.58945572,  51.54585769,  -0.        ,   0.        ])